language: java

jdk:
- oraclejdk8

sudo: false

install: true

script:
  - mvn -q install -PreducedMemory
  - mvn cobertura:cobertura

dist: trusty

cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2

after_success:
  - bash <(curl -s https://codecov.io/bash)