
--DROP TABLE CAMPUS_USER;


CREATE TABLE IF NOT EXISTS CAMPUS_USER(
	EMAIL		VARCHAR(30) PRIMARY KEY,	-- Key
	PASSWORD	VARCHAR(30),
	NAME		VARCHAR(30),
	SURNAME		VARCHAR(30),
	ROLE        VARCHAR(30) CHECK (ROLE = 'ADMIN' OR ROLE = 'WORKER' OR ROLE = 'PROFFESOR')
);
