
--DROP TABLE CAMPUS_USER;


CREATE TABLE IF NOT EXISTS CAMPUS_USER(
	EMAIL		VARCHAR(60) PRIMARY KEY,	-- Key
	PASSWORD	VARCHAR,
	NAME		VARCHAR(60),
	SURNAME		VARCHAR(60),
	ROLE        VARCHAR(10) CHECK (ROLE = 'ADMIN' OR ROLE = 'WORKER' OR ROLE = 'PROFFESOR')
);
